#==================================配置采集监控指标，抓取node-exporter的数据==================================

global:  #全局配置快，对所有采集任务生效
  scrape_interval: 15s  #全局采集间隔，每15秒去目标机器拉一次监控数据（包括CPU、内存、磁盘、网络等指标）
scrape_configs:  #采集任务列表，可写多个job
  - job_name: 'node'  #任务名称
    static_configs:  #静态配置
      - targets:  #监控目标列表
        - "172.23.187.46:9100"
        - "172.23.187.45:9100"
